// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: post.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    user_id,
    content
) VALUES (
    $1, $2
) RETURNING id, user_id, content, is_active, created_at, updated_at
`

type CreatePostParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Content string    `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Posts, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.UserID, arg.Content)
	var i Posts
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
